spring:
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
  application:
    name: Metrics Producer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/producer_db
    username: postgres
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: db/changelog/main-changelog.xml
security:
  jwt:
    secret-key: veryLongAndVerySecretKeyNoBodyWillEverGuessItBecauseItIsUnbelievablySecretOhMyLordSomeOneTryToGuessIt
server:
  port: 8081
topic:
  send-metrics: metrics-topic